name: Compilación automática_v2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Compilar código (Python ejemplo)
      run: |
        python -m py_compile main.py
        python -m py_compile test_main.py
    
    - name: Ejecutar programa
      run: |
        python main.py
